digitize:
  image: icr.io/ai-services-cicd/digitize-service:v0.0.74
  log_level: "INFO"
  database: "digitize_metadata"
  # @generate:password length=32, special=false
  dbEncryptionKey: ""
  resources:
    requests:
      cpu: "16"
      memory: "50Gi"
    limits:
      cpu: "16"
      memory: "50Gi"

digitizeUi:
  image: icr.io/ai-services-cicd/digitize-ui:v0.0.38
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      cpu: "50m"
      memory: "512Mi"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-6
  storage: 5Gi
  # @generate:password
  password: ""

