FROM registry.access.redhat.com/ubi9/ubi:9.7 AS builder
ARG ETCD_VERSION
ARG TARGETARCH

USER root

RUN dnf install -y --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms make && dnf clean all

ARG GO_VERSION=1.24.8

RUN curl -LO https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz && \
    tar -C /usr/local -xvf go${GO_VERSION}.linux-${TARGETARCH}.tar.gz && \
    rm -f go${GO_VERSION}.linux-${TARGETARCH}.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

RUN curl -fSL -o etcd.tar.gz https://github.com/etcd-io/etcd/archive/refs/tags/v${ETCD_VERSION}.tar.gz && \
    mkdir -p /etcd && \
    tar -zxf etcd.tar.gz -C /etcd --strip-components=1 && \
    rm -rf etcd.tar.gz && \
    cd /etcd && \
    make -j$nproc

FROM registry.access.redhat.com/ubi9/ubi-micro:9.7

COPY --from=builder /etcd/bin/etcd /usr/bin/etcd
COPY --from=builder /etcd/bin/etcdctl /usr/bin/etcdctl
COPY --from=builder /etcd/bin/etcdutl /usr/bin/etcdutl

EXPOSE 2379 2380
CMD [ "etcd" ]
