apiVersion: template.openshift.io/v1
kind: TemplateInstance
metadata:
  name: vllm-spyre-ppc64le-runtime
  labels:
    networking.kserve.io/visibility: cluster-local
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  template:
    metadata:
      name: vllm-spyre-ppc64le-runtime-template
      namespace: redhat-ods-applications
