apiVersion: v1
kind: Service
metadata:
  name: "invoice-processing-ui"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Values.templateID }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/component: invoice-processing-ui
  ports:
    - name: invoice-processing-ui
      port: 4101
      targetPort: 4101
      protocol: TCP
