apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "invoice-processing-cache"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Values.templateID }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "4Gi"
