apiVersion: v1
kind: Service
metadata:
  name: "invoice-processing-api"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Values.templateID }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/component: invoice-processing-api
  ports:
    - name: invoice-processing-api
      port: 4100
      targetPort: 4100
      protocol: TCP
